# sync-prompts.ps1
# Sync CLAUDE.md (canonical) -> GEMINI.md, AGENTS.md
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/sync-prompts.ps1

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir
$source = Join-Path $projectRoot "CLAUDE.md"

if (-not (Test-Path $source)) {
    Write-Error "CLAUDE.md not found at: $source"
    exit 1
}

$nl = [Environment]::NewLine
$header = "<!-- AUTO-GENERATED: Do not edit this file directly. Edit CLAUDE.md and run scripts/sync-prompts.ps1 -->" + $nl + $nl
$content = Get-Content $source -Raw -Encoding UTF8

$targets = @("GEMINI.md", "AGENTS.md")

foreach ($target in $targets) {
    $targetPath = Join-Path $projectRoot $target
    $output = $header + $content
    [System.IO.File]::WriteAllText($targetPath, $output, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Synced: CLAUDE.md -> $target"
}

Write-Host ""
Write-Host "Done. All prompt files are in sync."
